// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopifyAnalyticsApi.Data;

#nullable disable

namespace ShopifyAnalyticsApi.Migrations
{
    [DbContext(typeof(ShopifyDbContext))]
    [Migration("20260106234458_AddShopifyVariantIdAndTitleToProductVariants")]
    partial class AddShopifyVariantIdAndTitleToProductVariants
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // このファイルは自動生成されるため、簡易版を作成
            // 実際の適用時には、ShopifyDbContextModelSnapshot.csを更新する必要があります
#pragma warning restore 612, 618
        }
    }
}
