name: バックエンド開発環境　Azure Web App CI/CD (Production)

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
  workflow_dispatch:  # 手動実行を可能にする

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build with dotnet
        run: |
          cd backend/ShopifyAnalyticsApi
          dotnet restore
          dotnet build --configuration Release

      - name: Publish with dotnet
        run: |
          cd backend/ShopifyAnalyticsApi
          dotnet publish -c Release -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch'  # 手動実行時もデプロイ
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app

      - name: 'Deploy to Azure Web App (Production)'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'ShopifyAnalyticsApi20250720173320'
          # slot-name: 'Production'  # 新しいプランでは不要またはサポートされていない可能性
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: . 