name: Build and deploy ShopifyTestApi

on:
  push:
    branches:
      - develop
    paths:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      actions: read
      workflows: write
      deployments: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Debug - Workflow Information
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: |
          cd backend/ShopifyTestApi
          dotnet restore
          dotnet build --configuration Release

      - name: Debug - Check project structure
        run: |
          cd backend/ShopifyTestApi
          echo "Current directory: $(pwd)"
          echo "Project file exists: $(Test-Path ShopifyTestApi.csproj)"
          echo "Directory contents:"
          ls -la

      - name: Publish with dotnet
        run: |
          cd backend/ShopifyTestApi
          dotnet publish -c Release -o ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: backend/ShopifyTestApi/publish

  deploy:
    runs-on: windows-latest
    needs: build
    if: github.ref == 'refs/heads/develop' || github.event_name == 'workflow_dispatch'  # 手動実行時もデプロイ
    permissions:
      contents: read
      actions: read
      deployments: write
      id-token: write
    environment:
      name: 'Development'
      url: 'https://shopifyapp-backend-develop-a0e6fec4ath6fzaa.japanwest-01.azurewebsites.net/'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
      
      - name: Debug - Deploy Information
        run: |
          echo "Deploying to Azure App Service: shopifyapp-backend-develop"
          echo "Environment URL: https://shopifyapp-backend-develop-a0e6fec4ath6fzaa.japanwest-01.azurewebsites.net/"
          echo "Event type: ${{ github.event_name }}"
          echo "Branch: ${{ github.ref }}"

      - name: Deploy to Azure Web App (Development)
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'shopifyapp-backend-develop'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C60B318531324C8F9CC369407A7D3DF7 }}
          package: .
