name: Build and deploy ShopifyTestApi

on:
  push:
    branches:
      - develop
    paths:
      - 'backend/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'develop'
        type: choice
        options:
          - develop
          - staging
      force_deploy:
        description: 'Force deployment even if no changes'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      actions: read
      workflows: write
      deployments: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Debug - Workflow Information
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Actor: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Run ID: ${{ github.run_id }}"

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: |
          cd backend/ShopifyTestApi
          dotnet restore
          dotnet build --configuration Release

      - name: Debug - Check project structure
        run: |
          cd backend/ShopifyTestApi
          echo "Current directory: $(pwd)"
          echo "Project file exists: $(Test-Path ShopifyTestApi.csproj)"
          echo "Directory contents:"
          ls -la

      - name: Publish with dotnet
        run: |
          cd backend/ShopifyTestApi
          dotnet publish -c Release -o ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: backend/ShopifyTestApi/publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      contents: read
      actions: read
      deployments: write
      id-token: write
    
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'shopifyapp-backend-${{ github.event.inputs.environment || 'develop' }}'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_C60B318531324C8F9CC369407A7D3DF7 }}